// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package sys_resource

import (
	"github.com/gogf/gf/errors/gerror"
	"github.com/gogf/gf/frame/g"
)

// Fill with you ideas below.

func SeleteList(query *QueryParam) ([]*DaoEntity, int, error) {

	model := g.DB().Table("sys_resource as a").
		LeftJoin("sys_category as b", "b.cate_id = a.cate_id").
		LeftJoin("sys_user as c", "c.user_id = a.user_id").
		LeftJoin("sys_dict_data as d", "d.dict_value = a.resource_type").
		LeftJoin("sys_circle as e", "e.circle_id = a.circle_id")
	model.Where("d.dict_type", "sys_res_type")
	if query != nil {
		if query.ResourceTitle != "" {
			model.Where("a.resource_title like ?", "%"+query.ResourceTitle+"%")
		}
		if query.CateId != 0 {
			model.Where("a.cate_id =?", query.CateId)
		}
		if query.ResourceType != "" {
			model.Where("a.resource_type =?", query.ResourceType)
		}
		if query.Status != "" {
			model.Where("a.status =?", query.Status)
		}
		if query.StartTime != "" {
			model.Where("date_format(a.create_time,'%y%m%d') >= date_format(?,'%y%m%d')", query.StartTime)
		}
		if query.EndTime != "" {
			model.Where("date_format(a.create_time,'%y%m%d') <= date_format(?,'%y%m%d')", query.EndTime)
		}
	}
	if query.OrderByColumn != "" {
		query.OrderByColumn = "a." + query.OrderByColumn
		model.Order(query.OrderByColumn + " " + query.Sort)
	}
	model.Page(query.Page, query.Limit)
	total, err := model.Count()
	if err != nil {
		return nil, 0, gerror.New("查询错误")
	}
	model.Fields(`a.resource_id,
			a.resource_title,a.resource_type,
			a.cover,a.status,a.create_time,a.is_hot,
			b.cate_name,c.nick_name,d.dict_label,e.circle_name`)
	var result []*DaoEntity
	err = model.Structs(&result)
	if err != nil && result != nil {
		return nil, 0, gerror.New("查询错误")
	}

	return result, total, nil
}
